import {useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,CalendarDays} from 'lucide-react';

const events=[
 ['2026-07-27','Commencement of classes','class'],['2026-08-15','Independence Day','holiday'],['2026-08-26','Milad-un-Nabi','holiday'],['2026-09-04','Janmashtami','holiday'],['2026-09-14','MSE-1 begins','exam'],['2026-09-18','MSE-1 ends','exam'],['2026-10-02','Gandhi Jayanti','holiday'],['2026-10-19','Diwali Break begins','break'],['2026-10-23','Diwali Break ends','break'],['2026-11-09','MSE-2 begins','exam'],['2026-11-13','MSE-2 ends','exam'],['2026-12-04','Last teaching day','milestone'],['2026-12-07','ESE begins','exam'],['2026-12-18','ESE ends','exam']
] as const;
const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
const typeLabel={class:'Classes',holiday:'Holiday',exam:'Exam',break:'Break',milestone:'Milestone'} as const;
export function AcademicCalendar({month,setMonth}:{month:number;setMonth:(n:number)=>Promise<void>}){
 const year=2026,[selected,setSelected]=useState<string|null>(null),first=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate();
 const monthEvents=useMemo(()=>events.filter(e=>new Date(e[0]+'T00:00:00').getMonth()===month),[month]);
 const selectedEvent=events.find(e=>e[0]===selected);const change=(delta:number)=>{const n=Math.max(0,Math.min(11,month+delta));if(n!==month){setSelected(null);void setMonth(n)}};
 return <><header className="detailHead"><div><small>ACADEMIC CALENDAR · SEM 3</small><h1>{months[month]} {year}</h1></div></header><div className="calendarNav"><button onClick={()=>change(-1)} disabled={month===0}><ChevronLeft/></button><div><small>2026–27 ODD SEMESTER</small><b>{months[month]}</b></div><button onClick={()=>change(1)} disabled={month===11}><ChevronRight/></button></div><div className="calendarGrid">{['S','M','T','W','T','F','S'].map((x,i)=><small key={i}>{x}</small>)}{Array.from({length:first},(_,i)=><i key={'e'+i}/>)}{Array.from({length:days},(_,i)=>{const day=i+1,ev=monthEvents.find(e=>new Date(e[0]+'T00:00:00').getDate()===day);return <button aria-label={ev?`${day} ${ev[1]}`:`${day}`} className={`calendarDay${ev?' hasEvent '+ev[2]:''}${selected===ev?.[0]?' selected':''}`} key={day} onClick={()=>ev&&setSelected(selected===ev[0]?null:ev[0])}><b>{day}</b>{ev&&<span/>}</button>})}</div>{selectedEvent&&<div className={`calendarSelected ${selectedEvent[2]}`}><CalendarDays/><div><small>{typeLabel[selectedEvent[2]]}</small><b>{selectedEvent[1]}</b><span>{new Date(selectedEvent[0]+'T00:00:00').toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</span></div></div>}<div className="sectionTitle"><div><small>{months[month].toUpperCase()}</small><h2>Important dates</h2></div><span className="eventCount">{monthEvents.length} {monthEvents.length===1?'event':'events'}</span></div>{monthEvents.length?<div className="list calendarEvents">{monthEvents.map(e=><button className="calendarEvent" key={e[0]} onClick={()=>setSelected(e[0])}><i className={`eventDot ${e[2]}`}/><div><b>{e[1]}</b><span>{new Date(e[0]+'T00:00:00').toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'})}</span></div><em>{typeLabel[e[2]]}</em></button>)}</div>:<div className="emptyState"><CalendarDays/><b>No academic events</b><p>There are no Gradeflow calendar events for this month.</p></div>}</>
}