import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, Check, ChevronRight, PenLine, Sparkles, X } from 'lucide-react';
import { activeSemester, semesters } from '../data/academics';
import type { Mark } from '../types/academic';

type Flow='menu'|'manual'|'ai';
export function AddMarkSheet({open,onClose,onSave}:{open:boolean;onClose:()=>void;onSave:(mark:Omit<Mark,'id'|'createdAt'>)=>void}){
 const[flow,setFlow]=useState<Flow>('menu');
 useEffect(()=>{document.body.style.overflow=open?'hidden':'';if(!open)setFlow('menu');return()=>{document.body.style.overflow=''}},[open]);
 return <AnimatePresence>{open&&<><motion.button aria-label="Close" className="sheetShade" onClick={onClose} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.section className="mobileSheet" initial={{y:'100%'}} animate={{y:0}} exit={{y:'100%'}} transition={{type:'spring',stiffness:380,damping:34}}><div className="sheetGrab"/><div className="sheetScroll">{flow==='menu'?<Menu close={onClose} next={setFlow}/>:flow==='manual'?<Manual back={()=>setFlow('menu')} save={m=>{onSave(m);onClose()}}/>:<ComingSoon back={()=>setFlow('menu')}/>}</div></motion.section></>}</AnimatePresence>
}
function Head({title,sub,close}:{title:string;sub:string;close?:()=>void}){return <div className="sheetTitle"><div><small>QUICK ADD</small><h2>{title}</h2><p>{sub}</p></div>{close&&<button onClick={close}><X/></button>}</div>}
function Menu({close,next}:{close:()=>void;next:(f:Flow)=>void}){return <><Head title="Add to Gradeflow" sub="Choose what you want to record." close={close}/><button className="sheetAction" onClick={()=>next('ai')}><Sparkles/><div><b>Scan with AI</b><span>Review detected data before saving</span></div><ChevronRight/></button><button className="sheetAction" onClick={()=>next('manual')}><PenLine/><div><b>Enter marks manually</b><span>Fast subject and assessment entry</span></div><ChevronRight/></button><p className="sheetNote">Nothing changes until you confirm it.</p></>}
function Manual({back,save}:{back:()=>void;save:(m:Omit<Mark,'id'|'createdAt'>)=>void}){const sem=semesters.find(s=>s.id===activeSemester)!;const[subjectCode,setSubject]=useState(sem.courses[0].code),[assessment,setAssessment]=useState('MSE-1'),[score,setScore]=useState(''),[max,setMax]=useState('40'),[error,setError]=useState('');const submit=()=>{const s=Number(score),m=Number(max);if(!Number.isFinite(s)||!Number.isFinite(m)||s<0||m<=0||s>m){setError('Enter a valid score and maximum.');return}save({semester:activeSemester,subjectCode,assessment:assessment.trim()||'Assessment',score:s,max:m})};return <><button className="sheetBack" onClick={back}><ArrowLeft/> Back</button><Head title="Add marks" sub="Record an assessment in a few seconds."/><div className="sheetForm"><label>Subject<select value={subjectCode} onChange={e=>setSubject(e.target.value)}>{sem.courses.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label>Assessment<input value={assessment} onChange={e=>setAssessment(e.target.value)}/></label><div className="scoreInputs"><label>Score<input inputMode="decimal" value={score} onChange={e=>setScore(e.target.value)}/></label><label>Out of<input inputMode="decimal" value={max} onChange={e=>setMax(e.target.value)}/></label></div>{error&&<p className="formError">{error}</p>}<button className="sheetPrimary" onClick={submit}><Check/> Save marks</button></div></>}
function ComingSoon({back}:{back:()=>void}){return <><button className="sheetBack" onClick={back}><ArrowLeft/> Back</button><Head title="AI import" sub="The review-first flow is being connected to the secure backend."/><div className="emptyState"><Sparkles/><b>No fake detection</b><p>Gradeflow will only show extracted marks here when the real AI endpoint is connected.</p></div></>}
