import {useMemo,useState} from 'react';
import {Pencil,Trash2,X,Check,TrendingUp,Target} from 'lucide-react';
import type {Course,Mark} from '../types/academic';

export function SubjectDetail({course,marks,onUpdate,onDelete}:{course:Course;marks:Mark[];onUpdate:(id:string,patch:Partial<Mark>)=>Promise<unknown>;onDelete:(id:string)=>Promise<Mark|undefined>}){
 const[editing,setEditing]=useState<Mark|null>(null),[assessment,setAssessment]=useState(''),[score,setScore]=useState(''),[max,setMax]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const stats=useMemo(()=>{const scored=marks.reduce((n,m)=>n+m.score,0),total=marks.reduce((n,m)=>n+m.max,0),pct=total?scored/total*100:0;const latest=marks[0];return{scored,total,pct,latest}},[marks]);
 const edit=(m:Mark)=>{setEditing(m);setAssessment(m.assessment);setScore(String(m.score));setMax(String(m.max));setError('')};
 const save=async()=>{if(!editing)return;const s=Number(score),mx=Number(max);if(!assessment.trim())return setError('Assessment name is required.');if(!Number.isFinite(s)||!Number.isFinite(mx)||s<0||mx<=0||s>mx)return setError('Enter a valid score.');setBusy(true);setError('');try{await onUpdate(editing.id,{assessment:assessment.trim(),score:s,max:mx});setEditing(null)}catch(e){setError(e instanceof Error?e.message:'Could not update mark')}finally{setBusy(false)}};
 return <><div className="subjectHero"><small>{course.code}</small><h2>{course.name}</h2><p>{course.credits} credits · Grade estimate {course.gradePoint?.toFixed(1)??'—'}</p>{marks.length>0&&<div className="subjectProgress"><i style={{width:`${Math.min(100,stats.pct)}%`}}/></div>}</div>{marks.length>0&&<div className="subjectStats"><article><TrendingUp/><div><small>OVERALL</small><b>{stats.pct.toFixed(1)}%</b><span>{stats.scored} / {stats.total} recorded</span></div></article><article><Target/><div><small>ASSESSMENTS</small><b>{marks.length}</b><span>{stats.latest?`Latest: ${stats.latest.assessment}`:'Recorded'}</span></div></article></div>}<div className="sectionTitle"><div><small>ASSESSMENTS</small><h2>Recorded marks</h2></div></div>{marks.length?<div className="assessmentList">{marks.map(m=><article key={m.id}><div><b>{m.assessment}</b><span>{Math.round(m.score/m.max*100)}% · Semester {m.semester}</span></div><strong>{m.score} / {m.max}</strong><div className="rowActions"><button aria-label="Edit mark" onClick={()=>edit(m)}><Pencil/></button><button aria-label="Delete mark" onClick={()=>void onDelete(m.id)}><Trash2/></button></div></article>)}</div>:<div className="emptyState"><Target/><b>No marks for this subject</b><p>Use the center + button to record an assessment.</p></div>}{editing&&<><button className="sheetShade" aria-label="Close editor" onClick={()=>setEditing(null)}/><section className="mobileSheet marksEditSheet"><div className="sheetGrab"/><div className="sheetScroll"><div className="sheetTitle"><div><small>EDIT ASSESSMENT</small><h2>{course.name}</h2><p>Update this assessment in the shared Gradeflow marks data.</p></div><button onClick={()=>setEditing(null)} aria-label="Close"><X/></button></div><div className="sheetForm"><label>Assessment<input value={assessment} onChange={e=>setAssessment(e.target.value)} placeholder="MSE 1, Quiz, Assignment…"/></label><div className="scoreInputs"><label>Score<input inputMode="decimal" type="number" value={score} onChange={e=>setScore(e.target.value)}/></label><label>Out of<input inputMode="decimal" type="number" value={max} onChange={e=>setMax(e.target.value)}/></label></div>{error&&<p className="formError">{error}</p>}<button className="sheetPrimary" disabled={busy} onClick={()=>void save()}><Check/>{busy?' Saving…':' Save changes'}</button></div></div></section></>}</>;
}