import { useState } from 'react';
import { Pencil, Trash2, X, Check } from 'lucide-react';
import type { Course, Mark } from '../types/academic';

export function SubjectDetail({course,marks,onUpdate,onDelete}:{course:Course;marks:Mark[];onUpdate:(id:string,patch:Partial<Mark>)=>Promise<unknown>;onDelete:(id:string)=>Promise<Mark|undefined>}){
 const[editing,setEditing]=useState<Mark|null>(null),[score,setScore]=useState(''),[max,setMax]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const edit=(m:Mark)=>{setEditing(m);setScore(String(m.score));setMax(String(m.max));setError('')};
 const save=async()=>{if(!editing)return;const s=Number(score),mx=Number(max);if(!Number.isFinite(s)||!Number.isFinite(mx)||s<0||mx<=0||s>mx){setError('Enter a valid score.');return}setBusy(true);try{await onUpdate(editing.id,{score:s,max:mx});setEditing(null)}catch(e){setError(e instanceof Error?e.message:'Could not update mark')}finally{setBusy(false)}};
 return <><div className="subjectHero"><small>{course.code}</small><h2>{course.name}</h2><p>{course.credits} credits · Grade estimate {course.gradePoint?.toFixed(1)??'—'}</p></div><div className="sectionTitle"><div><small>ASSESSMENTS</small><h2>Recorded marks</h2></div></div>{marks.length?<div className="assessmentList">{marks.map(m=><article key={m.id}><div><b>{m.assessment}</b><span>{Math.round(m.score/m.max*100)}%</span></div><strong>{m.score} / {m.max}</strong><div className="rowActions"><button aria-label="Edit mark" onClick={()=>edit(m)}><Pencil/></button><button aria-label="Delete mark" onClick={()=>void onDelete(m.id)}><Trash2/></button></div></article>)}</div>:<div className="emptyState"><b>No marks for this subject</b><p>Use the center + button to record an assessment.</p></div>}{editing&&<div className="inlineEditor"><div className="inlineEditorHead"><b>Edit {editing.assessment}</b><button onClick={()=>setEditing(null)}><X/></button></div><div className="scoreInputs"><label>Score<input inputMode="decimal" value={score} onChange={e=>setScore(e.target.value)}/></label><label>Out of<input inputMode="decimal" value={max} onChange={e=>setMax(e.target.value)}/></label></div>{error&&<p className="formError">{error}</p>}<button className="sheetPrimary" disabled={busy} onClick={()=>void save()}><Check/>{busy?' Saving…':' Save changes'}</button></div>}</>;
}
