import React,{useState}from'react';import{createRoot}from'react-dom/client';import{AnimatePresence,motion}from'framer-motion';import{Home,ChartNoAxesCombined,Plus,BookOpen,UserRound,Sparkles,PenLine,Camera,ChevronRight,TrendingUp,X}from'lucide-react';import'./style.css';
type Tab='home'|'progress'|'semester'|'you';
const marks=[['Data Structures','31 / 40','78%'],['Linear Algebra','18 / 20','90%'],['Computer Organization','26 / 30','87%']];
function App(){const[tab,setTab]=useState<Tab>('home'),[add,setAdd]=useState(false);return <main className="app"><AnimatePresence mode="wait"><motion.section key={tab} className="screen" initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}} transition={{duration:.2,ease:[.2,.8,.2,1]}}>{tab==='home'?<HomeScreen/>:tab==='progress'?<Progress/>:tab==='semester'?<Semester/>:<You/>}</motion.section></AnimatePresence><nav><Nav icon={<Home/>} label="Home" on={()=>setTab('home')} active={tab==='home'}/><Nav icon={<ChartNoAxesCombined/>} label="Progress" on={()=>setTab('progress')} active={tab==='progress'}/><button className="add" onClick={()=>setAdd(true)}><Plus/></button><Nav icon={<BookOpen/>} label="Semester" on={()=>setTab('semester')} active={tab==='semester'}/><Nav icon={<UserRound/>} label="You" on={()=>setTab('you')} active={tab==='you'}/></nav><AnimatePresence>{add&&<AddSheet close={()=>setAdd(false)}/>}</AnimatePresence></main>}
function HomeScreen(){return <><header><div><small>THURSDAY · SEMESTER 3</small><h1>Good morning.</h1></div><button className="avatar">AP</button></header><motion.div className="hero" initial={{scale:.97,opacity:0}} animate={{scale:1,opacity:1}}><div className="heroTop"><span>PROJECTED SGPA</span><TrendingUp size={18}/></div><strong>8.74</strong><p>You're on track for your <b>8.50 target</b>.</p><div className="track"><i style={{width:'74%'}}/></div><footer><span>Current CGPA <b>8.11</b></span><span>Projected <b>8.36</b></span></footer></motion.div><div className="sectionTitle"><div><small>SEMESTER PULSE</small><h2>Right now</h2></div><button>View all <ChevronRight/></button></div><div className="quick"><article><small>ATTENDANCE</small><b>88.6%</b><span>Comfortable</span></article><article><small>MARKS ADDED</small><b>12</b><span>3 this week</span></article></div><div className="sectionTitle"><div><small>LATEST</small><h2>Recent marks</h2></div></div><div className="list">{marks.map((m,i)=><motion.div className="mark" key={m[0]} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:.05*i}}><div><b>{m[0]}</b><span>Internal assessment</span></div><div><strong>{m[1]}</strong><span>{m[2]}</span></div></motion.div>)}</div></>}
function Progress(){return <><header><div><small>YOUR DIRECTION</small><h1>Progress</h1></div></header><div className="simpleHero"><small>CURRENT CGPA</small><strong>8.11</strong><p>Explore where this semester can take you.</p></div><Menu title="CGPA Projection" sub="See your predicted end-semester CGPA"/><Menu title="Future Lab" sub="Simulate upcoming semesters and targets"/><Menu title="Prediction history" sub="Compare predicted vs official results"/></>}
function Semester(){return <><header><div><small>SEMESTER 3</small><h1>Your semester</h1></div></header><div className="simpleHero"><small>SEMESTER PROGRESS</small><strong>68%</strong><div className="track"><i style={{width:'68%'}}/></div></div><Menu title="Subjects" sub="Courses, credits and performance"/><Menu title="Marks" sub="Every assessment in one clean timeline"/><Menu title="Targets" sub="Set SGPA and subject goals"/></>}
function You(){return <><header><div><small>GRADEFLOW</small><h1>You</h1></div></header><div className="profile"><div className="bigAvatar">AP</div><h2>Your Gradeflow</h2><span>Semester 3 · CSE AI & ML</span></div><Menu title="Account & security" sub="Sign-in, devices and app lock"/><Menu title="Preferences" sub="Appearance, motion and notifications"/><Menu title="About Gradeflow" sub="Version 0.1 · Android"/></>}
function Menu({title,sub}:{title:string,sub:string}){return <button className="menu"><div><b>{title}</b><span>{sub}</span></div><ChevronRight/></button>}
function Nav({icon,label,on,active}:any){return <button className={active?'active':''} onClick={on}>{icon}<span>{label}</span></button>}
function AddSheet({close}:{close:()=>void}){return <><motion.div className="shade" onClick={close} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.div className="sheet" initial={{y:'105%'}} animate={{y:0}} exit={{y:'105%'}} transition={{type:'spring',damping:28,stiffness:320}}><div className="grab"/><div className="sheetHead"><div><small>QUICK ADD</small><h2>Add to Gradeflow</h2><p>What do you want to update?</p></div><button onClick={close}><X/></button></div><Action icon={<Sparkles/>} title="Scan with AI" sub="Screenshot, result or PDF" hot/><Action icon={<PenLine/>} title="Enter marks" sub="Add an assessment manually"/><Action icon={<Camera/>} title="Capture result" sub="Use your camera to scan marks"/><p className="privacy">Nothing changes until you review and confirm it.</p></motion.div></>}
function Action({icon,title,sub,hot}:any){return <button className={'action '+(hot?'hot':'')}><i>{icon}</i><div><b>{title}</b><span>{sub}</span></div><ChevronRight/></button>}
createRoot(document.getElementById('root')!).render(<App/>);